config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  devise_for :users 

  resources :users, only: %i[index show] do
    resources :posts, only: %i[index show new create destroy] do
      resources :comments, only: %i[new create destroy]
      resources :likes, only: %i[create destroy]
    end
  end

  post 'api_users/auth/login/', to: 'api/authentication#login', as: :user_login
  post 'api_users/sign_up', to: 'api/users#create',as: :user_signup
  get  'api_users/users_list', to: 'api/users#index',as: :list_all_users
  get  'api_users/get_user', to: 'api/users#show',as: :get_user
  get  'api_users/:user_id/posts_list', to: 'api/posts#index', as: :list_all_user_posts
  get  'api_users/:user_id/posts/:post_id/comments_list', to: 'api/comments#index', as: :list_all_user_post_comments
  post 'api_users/:user_id/posts/:post_id/comments', to: 'api/comments#create', as: :add_comment

  root to: 'users#index'
end

app/views/shared/_comment_container.html.erb
  <ul class='comments-container'>
    <%comments_data.each do |comment|%>
      <li class='comments-container--list'>
        <div><span class='commenter'><%=comment.author.name%></span> : <%=comment.text%>
        <% if can? :destroy ,comment %>
          <%= button_to 'Remove comment',user_post_comment_path(current_user,comment.post, comment), method: :delete,class:'remove-comment-btn' %>
        <% end %>
        </div>
      </li>
    <%end%>
  </ul>

app/views/shared/_flashes.html.erb
<% flash.each do |type, msg| %>
  <div class='flash-message'>
    <%= msg %>
  </div>
<% end %>

app/views/shared/_post.html.erb
<div class='post-container'>
  <h5 class='post-container--heading'>Post #<%=post_data.id%></h5>
  <p class='post-container--title'><%=post_data.title%></p>
  <p class='post-container--text'><%=post_data.text%></p>
  <p class='post-container--counter'>
    Comments: <%=post_data.comments_counter%>,Likes: <%=post_data.likes_counter%>
  </p>
  <div class='post-container--buttons'>
    <%= link_to 'Add Comment', new_user_post_comment_path(user_id:current_user.id,post_id:post_data.id),method: :get ,class: 'comment-btn'%>
    <%= button_to 'Like', user_post_likes_path(user_id:current_user.id,post_id:post_data.id),method: :post ,class: 'like-btn'%>
    
    <% if can? :destroy, post_data %>
      <%= button_to 'Delete post', user_post_path(current_user,post_data),method: :delete ,class: 'comment-btn'%>
    <%end%>
  </div>
</div>

<% unless post_data.comments_counter==0%>
  <%= render partial: 'shared/comment_container' ,locals:{comments_data: post_data.most_recent_comments}%>
<% end %>

app/views/shared/_post_details.html.erb
<div class='post-details'>
  <div class='post-details__header'>
  <h5 class='post-details--heading'>Post #<%=post_data.id%> by <%=post_data.author.name%></h5>
  <p class='post-details--counters'>Comments: <%=post_data.comments_counter%>,Likes: <%=post_data.likes_counter%></p>
  </div>
  <div post-details__body>
    <h2 class='post-details--title'><%=post_data.title%></h2>
    <p class='post-details--text'><%=post_data.text%></p>
  </div>
</div>

app/views/shared/_user.html.erb
<div class='user-container'>
  <img class='user-container__img' src=<%=user_data.photo%> alt='User image' height='150' width='150'>
  <div class='user-container__detail'>
    <h2 class='user-container--name'><%= user_data.name%></h2>
    <p class='user-container--post-counter'>Number of Posts: <%=user_data.posts_counter%></p>
  </div>
</div>