config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  devise_for :users 

  resources :users, only: %i[index show] do
    resources :posts, only: %i[index show new create destroy] do
      resources :comments, only: %i[new create destroy]
      resources :likes, only: %i[create destroy]
    end
  end

  post 'api_users/auth/login/', to: 'api/authentication#login', as: :user_login
  post 'api_users/sign_up', to: 'api/users#create',as: :user_signup
  get  'api_users/users_list', to: 'api/users#index',as: :list_all_users
  get  'api_users/get_user', to: 'api/users#show',as: :get_user
  get  'api_users/:user_id/posts_list', to: 'api/posts#index', as: :list_all_user_posts
  get  'api_users/:user_id/posts/:post_id/comments_list', to: 'api/comments#index', as: :list_all_user_post_comments
  post 'api_users/:user_id/posts/:post_id/comments', to: 'api/comments#create', as: :add_comment

  root to: 'users#index'
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments, foreign_key: :post_id
  has_many :likes, foreign_key: :post_id
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'

  validates :title, presence: true
  validates :title, length: { maximum: 250 }
  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def update_posts_counter
    author.increment!(:posts_counter)
  end

  def decrement_posts_counter
    author.decrement!(:posts_counter)
  end

  def most_recent_comments
    comments.order(created_at: :desc).includes(:post, :author).limit(5)
  end

  after_create :update_posts_counter
  after_destroy :decrement_posts_counter
end

app/controllers/api/posts_controller.rb
class Api::PostsController < ApplicationController
  protect_from_forgery with: :null_session
  before_action :authorize_request

  def index
    @user = User.find(params[:user_id])
    @posts = Post.where(author_id: @user.id)
    render json: @posts, status: :ok
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource
  def index
    @user = User.find(params[:user_id])
    @user_posts = @user.posts.all.includes(:comments)

    @current_user_id = current_user.id
  end

  def show
    @post = Post.where(author_id: params[:user_id]).where(id: params[:id])[0]
    @current_user_id = current_user.id
  end

  def new
    @post = Post.new
    render :new, locals: { post: @post }
  end

  def create
    @post = current_user.posts.new(post_params)
    @post.author_id = current_user.id

    respond_to do |format|
      format.html do
        if @post.save
          # Success message
          flash.now[:success] = 'Post created successfully'
          redirect_to user_posts_path(current_user.id)
        else
          # Error message
          flash.now[:error] = 'Error: Post creation failed'
          render :new, locals: { post: @post }
        end
      end
    end
  end

  def destroy
    @post = Post.find_by(id: params[:id], author_id: current_user.id)
    like = Like.find_by(post_id: @post.id)
    comment = Comment.find_by(post_id: @post.id)

    like.destroy if like.present?
    comment.destroy if comment.present?

    if @post.destroy
      # Success message
      flash.now[:success] = 'Post deleted successfully'
      redirect_to user_posts_path(current_user.id)
    else
      # Error message
      flash.now[:error] = 'Error: Post deletion failed'
      render :new, locals: { post: @post }
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/views/posts/index.html.erb
<%= render partial: 'shared/user' ,locals:{user_data: @user}%>
<%@user_posts.each do |post|%>
  <%= link_to user_post_path(user_id: post.author.id,id: post.id),method: 'get',class: 'post_link' ,id: post.title.downcase do%>
  <%= render partial: 'shared/post' ,locals:{post_data: post,current_user_id: @current_user_id}%>
  <%end%>
<%end%>

<div class='pagination-btn-box'>
<button class='pagination-btn'>Pagination</button>
</div>

app/views/posts/new.html.erb
<div class='form-box'>
<h1 class='form-box__heading'>Add New Post</h1>

<%=form_with model: @post,url: user_posts_url,method: :post,class: 'form-box__form' do |f|%>
  <div class='form-box__title'>
  <%= f.text_field :title,placeholder: 'Title' ,class: 'text-title'%>
</div>

<div class='form-box__text'>
  <%= f.text_area :text ,placeholder: 'Your post',class: 'text-area',cols: '30',rows: '5'%>
</div>

<%= f.submit "Create Post" ,class: 'form-box__submit' %>
<%end%>

</div>

app/views/posts/new_comment.html.erb
<div class='comment-form'>
<h2 class='comment-form__heading'>Add Comment</h2>

<%= form_with model: comment,url: comments_path ,method: :post,local: true, scope: :comment,class: 'comment-form__input' do |f|%>

<div class='comment-form__text'>
  <%= f.text_area :text ,placeholder: 'Put your comment here',rows: '4',cols: '30' ,class: 'comment-text-area'%>
</div>

<%= f.submit "Add Comment" ,class: 'comment-form__btn'%>
<%end%>
</div>

app/views/posts/show.html.erb
<%= render model: 'posts', partial: 'shared/post_details' ,locals:{post_data: @post}%>
<br>
<% unless @post.comments_counter==0%>
  <%= render partial: 'shared/comment_container' ,locals:{comments_data: @post.most_recent_comments}%> 
<% end %>