config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  devise_for :users 

  resources :users, only: %i[index show] do
    resources :posts, only: %i[index show new create destroy] do
      resources :comments, only: %i[new create destroy]
      resources :likes, only: %i[create destroy]
    end
  end

  post 'api_users/auth/login/', to: 'api/authentication#login', as: :user_login
  post 'api_users/sign_up', to: 'api/users#create',as: :user_signup
  get  'api_users/users_list', to: 'api/users#index',as: :list_all_users
  get  'api_users/get_user', to: 'api/users#show',as: :get_user
  get  'api_users/:user_id/posts_list', to: 'api/posts#index', as: :list_all_user_posts
  get  'api_users/:user_id/posts/:post_id/comments_list', to: 'api/comments#index', as: :list_all_user_post_comments
  post 'api_users/:user_id/posts/:post_id/comments', to: 'api/comments#create', as: :add_comment

  root to: 'users#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
     <title>Zelalem Blog App </title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link
			href="https://fonts.googleapis.com/css?family=Lato:100,300,400,700,900"
			rel="stylesheet"
		/>
  
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class='navbar'>
      <h1 class='navbar__logo'><%=link_to 'Blog App',users_path ,class: 'logo-link'%></h1>
      <ul class='navbar__links'>
        <li><%=link_to 'Home',root_path ,class: 'navbar__link'%></li>
        
        <% if user_signed_in? %>
          <li><%= link_to  'Add Post', new_user_post_path(user_id:current_user.id) ,class: 'navbar__link',method: :get%></li>
          <li><%= link_to "Log Out",destroy_user_session_path,data: { turbo_method: :delete } ,class: 'navbar__link'%></li>      
        <%else%>
          <li><%= link_to 'Log In' ,new_user_session_path,class: 'navbar__link'%></li>
          <li><%= link_to 'Sign Up' ,new_user_registration_path,class: 'navbar__link'%></li>
        <%end%>
      </ul>
    
    </div>
    <div>
    <%= render 'shared/flashes' %>
    <%= yield %>
    </div>
  </body>
</html>